spring.datasource.url=jdbc:h2:file:C:/Users/ninac/test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password 
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

resilience4j.circuitbreaker.instances.discountById.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.discountById.failure-rate-threshold=70
resilience4j.circuitbreaker.instances.discountById.wait-duration-in-open-state=10000
resilience4j.circuitbreaker.instances.discountById.permitted-number-of-calls-in-half-open-state=1
resilience4j.circuitbreaker.configs.default.register-health-indicator=true

spring.config.import=optional:configserver:http://localhost:8080

debug=true