spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:file:/C:/Users/Andreea ciurescu/Documents/Development/awbd/test
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  config:
    import:
        configserver:http://localhost:8888/


server:
  port: 8080

resilience4j:
  circuitbreaker:
    instances:
      discountById:
        minimum-number-of-calls: 5
        failure-rate-threshold: 70
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 1
    configs:
      default:
        register-health-indicator: true

debug: true

percentage:
  month: 5
  year: 7