spring:
  application:
    name: demo
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:file:C:/Users/Andreea ciurescu/Documents/Development/awbd/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update

resilience4j:
  circuitbreaker:
    instances:
      discountById:
        minimum-number-of-calls: 5
        failure-rate-threshold: 70
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"